# Development environment override
services:
    php:
        build:
            context: .
            target: frankenphp_dev
        volumes:
            #- ./frankenphp/certs:/etc/caddy/certs:ro
            - ./:/app
            - ./frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro
            - ./frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
        environment:
            FRANKENPHP_WORKER_CONFIG: watch
            #CADDY_SERVER_EXTRA_DIRECTIVES: "tls /etc/caddy/certs/tls.pem /etc/caddy/certs/tls.key"
            # See https://xdebug.org/docs/all_settings#mode
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
            APP_ENV: "${APP_ENV:-dev}"
        extra_hosts:
            # Ensure that host.docker.internal is correctly defined on Linux
            - host.docker.internal:host-gateway
        tty: true

    database:
        ports:
            - "5499:5432"
