version: '3'

services:
    database:
        image: postgres:${POSTGRES_VERSION:-15}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-main}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-main}
            POSTGRES_USER: ${POSTGRES_USER:-main}
        volumes:
            - db-data:/var/lib/postgresql/data:rw

volumes:
    db-data:
