- name: Pull job provider
  ansible.builtin.cron:
    name: "pull job provider"
    minute: "0"
    hour: "1"
    job: "php {{ ansistrano_release_path.stdout }}/bin/console app:job-provider:retrieve"
