name: "Lint ✅"

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    coding-style:
        name: Coding Style
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v4

            - name: "Install PHP with extensions"
              uses: shivammathur/setup-php@v2
              with:
                  coverage: "none"
                  extensions: intl, ctype, iconv
                  php-version: 8.3
                  tools: composer, symfony

            - name: "Cache phpcsfixer"
              uses: actions/cache@v4
              with:
                  path: var/.php-cs-fixer.cache
                  key: phpcsfixer-${{ github.sha }}
                  restore-keys: phpcsfixer-

            - name: "Composer install"
              uses: ramsey/composer-install@v3
              with:
                  working-directory: "tools/php-cs-fixer"

            - name: "PHP-CS-Fixer"
              run: ./tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --diff --dry-run

    linters:
        name: Linters
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v4

            - name: "Install PHP with extensions"
              uses: shivammathur/setup-php@v2
              with:
                  coverage: "none"
                  extensions: intl, ctype, iconv, gd
                  php-version: 8.3
                  tools: composer

            - name: "Composer install"
              uses: ramsey/composer-install@v3

            - name: Lint YAML files
              run: ./bin/console lint:yaml config --parse-tags

            - name: Lint Twig templates
              run: ./bin/console lint:twig templates --env=prod

            - name: Lint XLIFF translations
              run: ./bin/console lint:xliff translations

            - name: Lint Parameters and Services
              run: ./bin/console lint:container --no-debug

            - name: Lint Doctrine entities
              run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

            - name: Check if any dependencies are compromised
              run: composer audit

            - name: PHPStan
              run: ./vendor/bin/phpstan analyze

            - name: Rector
              run: ./vendor/bin/rector process --dry-run
