name: "Lint ✅"

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    coding-style:
        name: Coding Style
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v3

#            - name: PHP-CS-Fixer
#              uses: docker://oskarstark/php-cs-fixer-ga
#              with:
#                  args: --diff --dry-run
            - name: "Install PHP with extensions"
              uses: shivammathur/setup-php@v2
              with:
                  coverage: "none"
                  extensions: intl, pdo_sqlite, ctype, iconv
                  php-version: 8.2
                  tools: composer:v2, symfony

            - name: "PHP-CS-Fixer"
              run: make phpcsfix

    linters:
        name: Linters
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v3

            - name: "Install PHP with extensions"
              uses: shivammathur/setup-php@v2
              with:
                  coverage: "none"
                  extensions: intl, pdo_sqlite, ctype, iconv
                  php-version: 8.2
                  tools: composer:v2, symfony

            - name: "Set composer cache directory"
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: "Cache composer"
              uses: actions/cache@v3.2.1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-8.1-composer-${{ hashFiles('composer.lock') }}
                  restore-keys: ${{ runner.os }}-8.0-composer-

            - name: "Composer install"
              id: install
              run: composer install --no-interaction --no-progress

            - name: Lint YAML files
              if: always() && steps.install.outcome == 'success'
              run: ./bin/console lint:yaml config --parse-tags

            - name: Lint Twig templates
              if: always() && steps.install.outcome == 'success'
              run: ./bin/console lint:twig templates --env=prod

            - name: Lint XLIFF translations
              if: always() && steps.install.outcome == 'success'
              run: ./bin/console lint:xliff translations

            - name: Lint Parameters and Services
              if: always() && steps.install.outcome == 'success'
              run: ./bin/console lint:container --no-debug

            - name: Lint Doctrine entities
              if: always() && steps.install.outcome == 'success'
              run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

            - name: Check if any dependencies are compromised
              if: always() && steps.install.outcome == 'success'
              run: symfony check:security

            - name: PHPStan
              if: always() && steps.install.outcome == 'success'
              run: ./vendor/bin/phpstan analyze --level 1 src/

            - name: Rector
              if: always() && steps.install.outcome == 'success'
              run: ./vendor/bin/rector process --dry-run
